### ISSUE TITLE
Cannot read properties of undefined (reading 'groupDnProperty')

### ISSUE THREAD

**Issue by juulian98** [vesse/node-ldapauth-fork#101]
I think there is a typo in the code:
'optss'
![image](https://user-images.githubusercontent.com/62206873/175267106-3adf9792-537c-4e64-afbd-5cbfa1672761.png)

**Comment by vfilatov** [comment]
I just came into the same problem...

**Comment by vesse** [comment]
Yes sorry for delay, fixed now in 5.0.5
