### ISSUE TITLE
use bcrypt.js instead of bcrypt

### ISSUE THREAD

**Issue by japel** [vesse/node-ldapauth-fork#13]
would it be possible to change the dependency to becryptjs?
it is compatible to bcrypt, but does not have those aweful c++ dependencies

**Comment by vesse** [comment]
If it works I have nothing against the idea and a tested pull request would be welcome. The dependency was already made optional for the benefit of Windows users after which this probably is an issue only for vast minority of users.

**Comment by japel** [comment]
#14
