### ISSUE TITLE
The 'error' event returned by ldapjs not handled correctly

### ISSUE THREAD

**Issue by faacy** [vesse/node-ldapauth-fork#25]
This is causing an unhandled 'error' event when ever the connection to the LDAP server is down.

**Comment by nazrhyn** [comment]
In version 1.0.0 of [mcavage/node-ldapjs](/mcavage/node-ldapjs), it appears that the errors that were only being emitted but not passed to the callbacks are now also being passed to the callbacks. We've retracted our PR (vesse/node-ldapauth-fork#26) as this library does not appear to require any changes any longer. My PR vesse/passport-ldapauth#38 still remains as it is still needed.

In your library, you just need to update your dependencies to apply this fix.

**Comment by vesse** [comment]
Thanks, I was briefly looking over `ldapjs` changes just the other day and hopefully will have time on weekend to update the dependency.

**Comment by nazrhyn** [comment]
:+1: Awesome. I look forward to it.

**Comment by chriseckhardt** [comment]
Ran into this myself trying to get a sinopia installation running with an ldap plugin this week. Appreciate your work!

**Comment by vesse** [comment]
@nazrhyn At least DNS errors come still as uncaught, [this test](https://github.com/vesse/passport-ldapauth/blob/c48602a0298974cd3aeb479a0515966fd450eff6/test/strategy-test.js#L328-L343) fails with

```
  1) LDAP authentication strategy with invalid LDAP url should handle the error:
     Uncaught Error: getaddrinfo ENOTFOUND
      at errnoException (dns.js:37:11)
      at Object.onanswer [as oncomplete] (dns.js:124:16)
```
