### ISSUE TITLE
LDAP auth error InvalidCredentialsError

### ISSUE THREAD

**Issue by noorahmed94** [vesse/node-ldapauth-fork#34]
I am trying to connect ldap server using your library. The problem is i get the following error :

`LDAP auth error: InvalidCredentialsError: 80090308: LdapErr: DSID-0C0903D0, comment: AcceptSecurityContext error, data 52e, v2580`

I am using ldapsearch and its connecting to the ldap server, here is my ldapsearch command :

`ldapsearch -H "ldap://10.XX.XX.X:389" -x -D "test\user.test" -w "password" -b "DC=domain,DC=org" "(uid=john)"`

SImilarly, When i use library to connect to the ldap server using :

```
var ldap = new LdapAuth({
        url:"ldap://10.XX.XX.X:389",
        bindDn: "test\user.test",
        bindCredentials: "password",
        searchBase: "DC=domain,DC=org",
        searchFilter: "(uid=john)",
        cache: false,
        verbose : true
    });
    ldap.authenticate("username", "password", function (err, user) {
        if (err) {
        console.log("LDAP auth error: %s", err);
        }
    });
```

Please guide me through the issue i am facing.

**Comment by dimitertodorov** [comment]
bindDn Should be the full DN of the User.
e.g.
```
CN=user.test,OU=Users,DC=domain,DC=org
```

**Comment by noorahmed94** [comment]
@dimitertodorov Same issue continues to appear, Same error

**Comment by dimitertodorov** [comment]
Are you sure you have the correct DN. It has to match exactly
What is the output of:
```
ldapsearch -H "ldap://10.XX.XX.X:389" -x -D "test\user.test" -w "password" -b "DC=domain,DC=org" "(uid=user.test)"
```

**Comment by noorahmed94** [comment]
@dimitertodorov yes it exactly matches

```
# extended LDIF
#
# LDAPv3
# base <DC=domain,DC=org> with scope subtree
# filter: (uid=john)
# requesting: ALL
#

# search reference
ref: ldap://DomainDnsZones.domain.org/DC=DomainDnsZones,DC=domain,DC=o
 rg

# search reference
ref: ldap://ForestDnsZones.domain.org/DC=ForestDnsZones,DC=domain,DC=o
 rg

# search reference
ref: ldap://domain.org/CN=Configuration,DC=domain,DC=org

# search result
search: 2
result: 0 Success

# numResponses: 4
# numReferences: 3
```

**Comment by dimitertodorov** [comment]
What about something like this:
```
# 
ldapsearch -x -D "srv.user@domain.org" -W -p 389 -h 10.0.0.44 \
   -b "dc=domain,dc=org" -s sub "(sAMAccountName=todorovdi)" dn
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <dc=domain,dc=org> with scope subtree
# filter: (sAMAccountName=todorovdi)
# requesting: dn
#

# Dimiter Todorov, Tools and Automation, iSERV Users, domain.org
dn: CN=Dimiter Todorov,OU=Bubbles,OU=Users,dc=domain,dc=org

# search reference
ref: ldap://DomainDnsZones.domain.org/DC=DomainDnsZones,dc=domain,dc=org

# search result
search: 2
result: 0 Success

# numResponses: 3
# numEntries: 1
# numReferences: 1
```

**Comment by noorahmed94** [comment]
@dimitertodorov yes it works for me in ldap search if my filter is sAMAccountName, similar output as yours. The thing is its not working in nodejs if i give same parameters.

**Comment by vesse** [comment]
Could you check if what you have [here in the user object](https://github.com/vesse/node-ldapauth-fork/blob/a9f01b47e55860b0272f558c3df013a0ebe832d8/lib/ldapauth.js#L341) is expected?

**Comment by JCarlos12** [comment]
does this already support sasl?
