### ISSUE TITLE
ldapClient.close() times-out frequently

### ISSUE THREAD

**Issue by ORESoftware** [vesse/node-ldapauth-fork#45]
I have this code:

```js
   let ldap;
    try {
      ldap = new LdapAuth(config.ldap);
    } catch (err) {
      console.error(err);
      return cb(err);
    }

/// some time later...

  ldap.close(function(err){
       // sometimes this doesn't get called
    });
```

from my testing, it appears that the `ldap.close()` call times out frequently, might there be a good reason for that? no idea why

**Comment by vesse** [comment]
I noticed problems with that too at least when an error is omitted. No idea why though, `close` just calls `unbind` to both the clients. Maybe look into ldapjs if you could identify something from there?
