### ISSUE TITLE
Connection Error: closed

### ISSUE THREAD

**Issue by khayalan-mathew** [vesse/node-ldapauth-fork#48]
Hey dear folks,

ive got the following issue. When i try to connect it throws this error

[21:21:05] [ERROR] - { ConnectionError: 1__ldap://192.168.3.2:636 closed
    at /home/appuser/apitest/node_modules/ldapjs/lib/client/client.js:1277:17
    at Array.forEach (native)
    at Client._onClose (/home/appuser/apitest/node_modules/ldapjs/lib/client/client.js:1272:19)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
  lde_message: '1__ldap://192.168.3.2:636 closed',
  lde_dn: null }

The config follows linuxmuster.net , but here the ldapoptions
const ldapoptions = {
  url: config.ldap,
  searchBase: 'ou=accounts,dc=linuxmuster,dc=local',
  searchFilter: '(uid={{username}})',
  reconnect: true
}

Somebody know the problem/error? And can help me out with this ^^

**Comment by vesse** [comment]
Try with command line tool `ldapsearch`:

```bash
ldapsearch \
  -H ldap://<host>:<port> \
  -x \
  -b ou=accounts,dc=linuxmuster,dc=local \
  "(uid=<existing username>)"
```

Are you not providing bind credentials? If not, are you sure the server supports anonymous access - they often don't, and at least quick googling about linuxmuster ldap led to [this page](http://docs.linuxmuster.net/en/latest/howtos/radius/ldap.html) which does set bind credentials in the example. If you are, add these to the command above: `-D <bindDN> -w <bindCredentials>`

Also, these kind of questions belong to [stackoverflow](https://stackoverflow.com/) and not GitHub issues.

**Comment by khayalan-mathew** [comment]
Thanks for help :) I know my problem now but i dont know how to solve it. This command works perfectly fine.

> LDAPTLS_REQCERT=never ldapsearch -x -H ldaps://[serveraddress] -b "dc=linuxmuster,dc=local" "(uid=[username]"

The "LDAPTLS_REQCERT=never" makes the difference, but i dont know how to make such a thing in this package i tried to include this in the ldapoptions
tlsOptions: {
    rejectUnauthorized: false
  }
Its the best guess i could make from docs... But it didnt help :)

**Comment by vesse** [comment]
If the options [here](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) don't work around then maybe just google if/how Node TLS connection can be made to skip the certificate validations. Or set up a free SSL certificate from letsencrypt.

**Comment by khayalan-mathew** [comment]
So currently im stuck... And cant help myself though google and co.
This is my current code
`const LDAPAuth = require('ldapauth-fork');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

const ldapoptions = {
  url: "ldaps://192.168.3.2:663",
  searchBase: 'ou=accounts,dc=linuxmuster,dc=local',
  searchFilter: '(&(objectClass=*)(uid={{username}}))',
  reconnect: true,
  tlsOptions: {
    rejectUnauthorized: false,
    requestCert: true
  }
}
const auth = new LDAPAuth(ldapoptions);
auth.authenticate('pompema', 'o3DvczFD', (err, user) => {
  if(err) {
    console.error(err);
  } else {
    console.log('Logged in');
    console.log(user);
  }
});
`
The "funny" thing is, that i didnt get any message at all neither error or success and this for hours

**Comment by vesse** [comment]
Maybe attach the error event listener for more errors. But really I don't know how you get the connection working with (apparently invalid) certificate, and this is a forum with very limited audience so you probably won't get any more help here. I still suggest Stackoverflow, or maybe `ldapjs` which is the library this one uses (but this is not their issue either).

**Comment by xiashulin** [comment]
> Hey dear folks,
> 
> ive got the following issue. When i try to connect it throws this error
> 
> [21:21:05] [ERROR] - { ConnectionError: 1__ldap://192.168.3.2:636 closed
> at /home/appuser/apitest/node_modules/ldapjs/lib/client/client.js:1277:17
> at Array.forEach (native)
> at Client._onClose (/home/appuser/apitest/node_modules/ldapjs/lib/client/client.js:1272:19)
> at Socket.g (events.js:292:16)
> at emitOne (events.js:96:13)
> at Socket.emit (events.js:188:7)
> at TCP._handle.close [as _onclose] (net.js:497:12)
> lde_message: '1__ldap://192.168.3.2:636 closed',
> lde_dn: null }
> 
> The config follows linuxmuster.net , but here the ldapoptions
> const ldapoptions = {
> url: config.ldap,
> searchBase: 'ou=accounts,dc=linuxmuster,dc=local',
> searchFilter: '(uid={{username}})',
> reconnect: true
> }
> 
> Somebody know the problem/error? And can help me out with this ^^

		
I also have this problem. How did you solve it?

**Comment by khayalan-mathew** [comment]
TLS-Options have to be like
```
tlsOptions: {
		rejectUnauthorized: false,
		requestCert: true
	}
```
