### ISSUE TITLE
angular2 ldap authentication

### ISSUE THREAD

**Issue by paragonda1** [vesse/node-ldapauth-fork#51]
Is there anyway to implement ldap authentication in angular2 by using server side script? I am trying to migrate my web application to Angular2 and I am done with most of the UI part now I left with Authentication. I have used LDAP as a web reference in my .net project. ldap authentication in the past app where I connect to my ldaps://example.host:636/ with userDN and password. I am looking for the way to do authentication using ldap. I looked into this link (https://auth0.com/authenticate/angular2/ldap) but didn't get where to register or give my ldap server details to work with, think that is available for paid users. Please suggest me the best way to implement authentication for Angular2 without any other extra cost by using server side scripting....

**Comment by vesse** [comment]
Use Stackoverflow for such questions. And consider checking how to use [Passport](http://passportjs.org/) with Angular 2. This library has a [passport strategy wrapper library](https://github.com/vesse/passport-ldapauth)
