### ISSUE TITLE
while authnecating users in ldap server using ldapauth-fork i am getting    no such user: "adminstrator@xyz.com"

### ISSUE THREAD

**Issue by rushendragangalapudi** [vesse/node-ldapauth-fork#56]
![screenshot from 2017-11-06 14-48-47](https://user-images.githubusercontent.com/33284688/32433652-a31fab12-c2d3-11e7-9676-e257264161fe.png)

**Comment by vesse** [comment]
This is more of a Stackoverflow material. But you should use `{{username}}` in search filter.
