### ISSUE TITLE
Cannot authenticate without Admin binding.

### ISSUE THREAD

**Issue by dejavu1987** [vesse/node-ldapauth-fork#58]
The documentation says:
Admin connection DN, e.g. `uid=myapp,ou=users,dc=example,dc=org`. Optional. If not given at all, admin client is not bound. Giving empty string may result in anonymous bind when allowed.

I tried both removing the option bindDn and using empty string but I am getting following response.

> Error:  { OperationsError: 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection.,

**Comment by vesse** [comment]
If your LDAP server requires a successful bind to be completed, then you do need to bind.

**Comment by Acetylen3** [comment]
@vesse Sorry for bringing up this old thread. However. is there any successful example of node-ldap authentication without admin binding? I have been trying using usernamefield and passwordfield in server config to login, but no luck.
I'm using https://github.com/sbrannstrom/nestjs-passport-ldap-example/ for testing.
