### ISSUE TITLE
allow {{username}} in groupSearchFilter

### ISSUE THREAD

**Issue by velrest** [vesse/node-ldapauth-fork#62]
I think `{{username}}` should be available in the `groupSearchFilter`.
This would require to edit this [line](https://github.com/vesse/node-ldapauth-fork/blob/master/lib/ldapauth.js#L116). This would allow to filter groups by `memberUid`.

I would gladly open a PR if this is acceptable.

**Comment by vesse** [comment]
Yes of course, please open a PR. I’m very open to all PRs if they serve a purpose for more than one spesific use case :)

**Comment by vesse** [comment]
Thanks. I merged the PR and then looked at the code base and remembered that `groupSearchFilter` can be a function too, so you could have achieved this without a PR by passing 

```javascript
const opts = {
  ...
  groupSearchFilter: (user) =>
    'yoursearchfilter'
      .replace(/{{dn}}/g, user[opts.groupDnProperty])
      .replace(/{{username}}/g, user.uid)
};
```

But, it's fine having that in the default one too. I'll see what to do with another PR and then release this at some point.
