### ISSUE TITLE
jpegPhoto decoding

### ISSUE THREAD

**Issue by mattiaa95** [vesse/node-ldapauth-fork#63]
when the user object shows up I am trying to save the jpegPhoto to a file for use as the profile pic. But I cannot figure out the format

I have tried (among many other things):
`fs.writeFileSync(jpgPath, ldapUser.jpegPhoto);`

And

```javascript
var jpg = new Buffer(ldapUser.jpegPhoto, 'base64');
fs.writeFileSync(jpgPath, jpg);
```
And
```javascript
  var img64 = Buffer.from(user.jpegPhoto).toString('base64');
  var foto = "<div><img src='data:image/jpeg;base64,"+img64+"'/></div>"
            fs.appendFile('index.html', foto, function (err) {
              if (err) throw err;
              console.log('Saved!');
            });
```

Thanks!

**Comment by vesse** [comment]
I have no idea about the format. However there is an option that is likely helpful. From the readme:

> **includeRaw** - Optional, default false. Set to true to add property `_raw` containing the original buffers to the returned user object. Useful when you need to handle binary attributes

ldapjs return object is an UTF-8 representation and likely you cannot get the binaries working with that, but they should work with raw buffers.

**Comment by vesse** [comment]
Yes, it appears as `user._raw`
