### ISSUE TITLE
Pull in PR 497 from node-ldapjs to fix `close` on Node 10

### ISSUE THREAD

**Issue by sarus** [vesse/node-ldapauth-fork#73]
Any chance this PR could be merged into this project?  This is to resolve `close` not working on Node 10

https://github.com/joyent/node-ldapjs/pull/497

Thank you!

**Comment by vesse** [comment]
You mean I'd change the dependency to the forked `ldapjs` from github? Unfortunately not. I cannot merge the PR to `node-ldapjs` naturally as I'm not a maintainer there.

**Comment by vesse** [comment]
It seems that @joyent has abandoned `ldapjs` completely. Many have switched to [ldapts](https://www.npmjs.com/package/ldapts) and probably this module should too.

**Comment by KaiserWolfTaco** [comment]
Any word on when this will transfer to ldapts? Thanks

**Comment by vesse** [comment]
Probably never as I am not really using this library myself anymore and rewriting without real use case might be a bit hazardous. `ldapjs` however started to show some signs of living and they've actually prepared a [release candidate](https://github.com/ldapjs/node-ldapjs/tree/next), but now it's been silent again. I've published an RC too that uses the RC version of `ldapjs` and thus works with new Node versions too. `npm i ldapauth-fork@next`
