### ISSUE TITLE
moment.js dependency

### ISSUE THREAD

**Issue by onhate** [vesse/node-ldapauth-fork#74]
I noticed my application is including moment.js as indirect dependency and it's coming from ldapauth-fork package, I've read the code and didn't find a usage of moment in this repository, is this dependency needed? considering it's 370Kb it would be good to remove.

**Comment by vesse** [comment]
Hmm true, wonder how that got there. I'll remove the direct dependency but it wont matter much since `ldpajs` requires `bunyan` and it requires `moment`, so it will be installed anyways.

**Comment by vesse** [comment]
Removed from 4.1.1
