### ISSUE TITLE
LdapAuth.prototype.close callback not called

### ISSUE THREAD

**Issue by FranckFreiburger** [vesse/node-ldapauth-fork#75]
https://github.com/vesse/node-ldapauth-fork/blob/f4f9f30c7e5986cd647f03384ca7e9b1f7fbee15/lib/ldapauth.js#L155-L157

AFAICS, it seems that you are waiting for a callback that will never be called ?
See: https://github.com/joyent/node-ldapjs/blob/master/lib/client/client.js#L844-L847

**Comment by vesse** [comment]
The callback is passed to [`Client.prototype._send`](https://github.com/joyent/node-ldapjs/blob/master/lib/client/client.js#L867) and from there to [`Client.prototype._sendSocket`](https://github.com/joyent/node-ldapjs/blob/master/lib/client/client.js#L1363). Then it becomes little unclear to follow without getting deeper into the implementation, but if you eg. add logging to [close callback in `passport-ldapauth`](https://github.com/vesse/passport-ldapauth/blob/88bb8e5c9a398382d7b2b51c0a87bfc84aa724fd/lib/passport-ldapauth/strategy.js#L278) and run the tests you'll see the callback is called.

**Comment by FranckFreiburger** [comment]
Thank you for the clarification
