### ISSUE TITLE
Log bunyan

### ISSUE THREAD

**Issue by jbperrin88** [vesse/node-ldapauth-fork#77]
Hi there,

I'm indirectly using your module via https://github.com/travisghansen/external-auth-server.

I would like to debug my ldap paremeter cause filter don't work well and i see the parameter LOG.

I've no idea how to use it , can you please help me ?

Thanks

**Comment by vesse** [comment]
You need to install [bunyan](https://github.com/trentm/node-bunyan), create a new logger instance, and pass the instance in the options like [here]( https://github.com/vesse/node-ldapauth-fork/blob/master/test/test.ts) 

See bunyan documentation for how to use it.
