### ISSUE TITLE
VerifyCredentials and LdapAuth

### ISSUE THREAD

**Issue by tactusoft** [vesse/node-ldapauth-fork#78]
Hi, From Colombia thanks for this libs. But I have a Question. I am using UserService of loopback/security.
This asynchronous library called verifyCredentials and returns a promise. How do I make auth.authenticate wait to return the promise? Thank you very much.

```
async verifyCredentials(credentials: Credentials): Promise<Usuario> {
auth.authenticate(username + '@upra.local', credentials.contrasenia, (err, user) => {
        console.error('LdapAuth: ', err);
        if (!err) {
          console.error('LdapAuth: ', user);
          return new Usuario();
        } else {
          throw new HttpErrors.Unauthorized(invalidCredentialsError);
        }
      });

        return new Usuario();
}
```

**Comment by vesse** [comment]
Maybe like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#Creating_a_Promise_around_an_old_callback_API)
