### ISSUE TITLE
[Question] nested group

### ISSUE THREAD

**Issue by Dan33l** [vesse/node-ldapauth-fork#81]
Hi,

I have the following LDAP structure where user account U is inside group B , and group B is inside group A. And i would like to allow access to users present inside nested groups of group A.

I made some tests but was not able to get a working setup.

So my question : is it possible to use nested group ?

**Comment by vesse** [comment]
No idea. If it works with `ldapjs` then yes. In general, better ask [Stackoverflow](https://stackoverflow.com/)
