### ISSUE TITLE
Connection to WINDOWS error

### ISSUE THREAD

**Issue by JTrotta** [vesse/node-ldapauth-fork#98]
Hello.
I'm trying to connect to a WS domain with no success,  using:
        "url": "ldap://x.x.x.x:389",
        "bindDN": "CN=Administrator,OU=GROUPA,CN=Users,DC=domain,DC=local",
        "bindCredentials": "password",
        "searchBase": "DC=domain,DC=local",
        "searchFilter": "(uid={{username}})"

On windows I got these errors:

1. 00000057: LdapErr: DSID-0C0C0095, comment: Error decoding ldap message, data 0, v4563
2. 87 The parameter is incorrect. Internal ID: c0c0095

Any help?

**Comment by JTrotta** [comment]
Anyone have an example configuration working with AD?

**Comment by vesse** [comment]
I cannot provide support, especially cannot do that for environment spesific problems. The last time I personally used this library with AD I added cobfig example to the passport.js plugin version of this to https://github.com/vesse/passport-ldapauth/#active-directory-over-ssl-example

Maybe try Stackoverflow?
